version: '3.8'

services:
  symfony:
    build:
      context: ./symfony-service
      dockerfile: Dockerfile
    image: symfony-app
    container_name: symfony-app
    ports:
      - "8080:80"
    volumes:
      - ./symfony-service:/var/www/html
    depends_on:
      - db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=recipe_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
    networks:
      - api

  express:
    build:
      context: ./express-service
      dockerfile: Dockerfile
    image: express-app
    container_name: express-app
    ports:
      - "3006:3006"
    volumes:
      - ./express-service:/usr/src/app
    env_file:
      - ./express-service/.env
    networks:
      - api

  db:
    image: mysql:5.7
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: recipe_db
    volumes:
      - db_data:/var/lib/mysql
      - db_data:/var/log/mysql
    networks:
      - api
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadminmulti
    restart: always
    depends_on:
      - db
    ports:
    - "8081:80"
    networks:
      - api  
  web-interface:
    build:
      context: ./web-interface
      dockerfile: Dockerfile
    image: web-interface-app
    container_name: web-interface-app
    ports:
      - "3001:3001"
    networks:
      - api

volumes:
  db_data:

networks:
  api:
